name: 'Update profile'
on:
  schedule:
    - cron: "0 */4 * * *" # every 4 hours
  workflow_dispatch:
  
jobs:
  install-quicklisp-on-tier-1-platforms:
    strategy:
      matrix:
        implementation: ['sbcl']
        os: ['ubuntu-latest']
    runs-on: '${{ matrix.os }}'
    name: 'Install Common Lisp'
    steps:
      - uses: actions/checkout@v3
      - uses: melusina-org/setup-common-lisp@v1
        with:
          implementation: '${{ matrix.implementation }}'
      - uses: melusina-org/setup-quicklisp@v1
        id: 'quicklisp'
        with:
          implementation: '${{ matrix.implementation }}'
      - name: 'Validate installed implementation'
        run: |
          test -d '${{ steps.quicklisp.outputs.quicklisp-home }}'
          test -d '${{ steps.quicklisp.outputs.quicklisp-local-projects }}'
      - name: Install libssl1.1
        run: sudo apt-get install -y libssl-dev
      # - name: 'Recompiles the binary'
      #   run: sbcl --load main.lisp --eval '(sb-ext:save-lisp-and-die "profile" :executable t :toplevel \'main)'
      - name: 'Runs the SBCL Binary'
        run: ./profile
